### ISSUE TITLE
Image missing "bootstrap-example.png"

### ISSUE THREAD

**Issue by cforcomputer** [UWB-ACM/Hackathon-Docs#16]
[https://docs.uwbhacks.com/build-a-website/responsive-css](https://docs.uwbhacks.com/build-a-website/responsive-css) is missing the linked image labeled `bootstrap-example.png`

**Comment by etcadinfinitum** [comment]
@cforcomputer i noticed this a while back. the image was linked under the same directory but filepath had "uploads/bootstrap-example.png" iirc. This _should_ be fixed with PR #15 which reorged pages for this doc (and others). Could you take a look and let me know if you see any immediate problems?

**Comment by cforcomputer** [comment]
Ah my apologies, I didn't see that you had requested my review.
